language: go

go:
  - 1.12.x

go_import_path: github.com/appsody/appsody

services:
  - docker

# skip the default language's install and script steps, we implement job stages instead
install: skip
script: skip

stages:
  - name: lint
  - name: test
  - name: deploy
    if: tag IS present

     
test-template: &test-template
  stage: test
  install: if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make; fi
  script: make cover

jobs:
  include:
    - name: Lint
      stage: lint
      os: linux
      script: make lint
    - <<: *test-template
      name: Full Test on Linux
      os: linux
      # installation instructions for Buildah taken from https://github.com/containers/buildah/blob/master/install.md
      dist: xenial
      before_install:
       - . /etc/os-release
       - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${ID^}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
       - wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${ID^}_${VERSION_ID}/Release.key -O Release.key
       - sudo apt-key add - < Release.key
       -  sudo apt-get update -qq
       -  sudo apt-get -qq -y install buildah
    - <<: *test-template
      name: Unit Test on MacOS
      os: osx
      script: make unittest
    - <<: *test-template
      name: Unit Test on Windows
      os: windows
      script: 
      - make unittest
    - name: Deploy Release
      stage: deploy
      os: linux
      script:
        - make VERSION=${TRAVIS_TAG}  package
        - make deploy
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GH_TOKEN
        file: package/*
        file_glob: true
        on:
          branch: master
          tags: true
